# Default values for evaluation-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

##################################
# Evaluation Proxy Configuration #
##################################

evaluationProxy:
  # An array of projects with deployments for the evaluation proxy to manage. You must specify values for `id`,
  # `apiKey`, `secretKey`, and at least one entry in `deploymentKeys`. Deployment keys must be of the `server` type.
  projects:
      # The project ID. Can be found in the project settings in Amplitude.
    - id: ""
      # The project's API key. Can be found in the project settings in Amplitude.
      apiKey: ""
      # The project's secret key. Can be found in the project settings in Amplitude.
      secretKey: ""
      # The keys of the deployments for the evaluation proxy to manage. Evaluations are only available for flags
      # associated with deployments that are listed here. These deployments live within the project defined by the
      # project ID.
      deploymentKeys:
        - ""

  configuration:
    # The configuration for redis. If missing, proxy instances will run without persistence (in memory).
    redis:
      # The URI to connect to redis with. Should contain the protocol, host, port, and any other username, password,
      # and path for connection.
      uri: ""

#############################
# Kubernetes  Configuration #
#############################

replicaCount: 2

image:
  repository: amplitudeinc/evaluation-proxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  # Default evaluation proxy port. If you want to change this port you must also update the port in
  # `evaluationProxy.configuration.port`
  port: 3546
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
